services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    restart: always

  db:
    image: postgres:18-alpine
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - "database:/var/lib/postgresql/18/docker"
    restart: always

volumes:
  database:
